# 𝐑𝐍𝐍 𝐈𝐦𝐩𝐥𝐞𝐦𝐞𝐧𝐭𝐚𝐭𝐢𝐨𝐧 𝐨𝐟 𝐦𝐨𝐯𝐢𝐞 𝐃𝐚𝐭𝐚 :

In [1]:
# Import library :
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import Tokenizer

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [6]:
# Create data :
data = [
    ("I absolutely loved this movie!", "positive"),
    ("The acting was terriable and the plot was boaring","negative"),
    ("This film was masterpeace.", "positive"),
    ("I couldn't stand watching it, a complete waste of time", "negative"),
    ("The cinematography was stunning , a must watch", "positive")
]

In [7]:
reviews, settiments = zip(*data)

In [8]:
reviews

('I absolutely loved this movie!',
 'The acting was terriable and the plot was boaring',
 'This film was masterpeace.',
 "I couldn't stand watching it, a complete waste of time",
 'The cinematography was stunning , a must watch')

In [9]:
settiments

('positive', 'negative', 'positive', 'negative', 'positive')

In [10]:
# Create & instance of the tokenizer class :
tokens = Tokenizer()
tokens.fit_on_texts(reviews)

In [11]:
# Claculate the vocabulary size :
vocab_size = len(tokens.word_index)+1
vocab_size

28

In [12]:
# Convert the texts into sequences of integers :
seq = tokens.texts_to_sequences(reviews)
seq

[[3, 6, 7, 4, 8],
 [2, 9, 1, 10, 11, 2, 12, 1, 13],
 [4, 14, 1, 15],
 [3, 16, 17, 18, 19, 5, 20, 21, 22, 23],
 [2, 24, 1, 25, 5, 26, 27]]

In [13]:
# Count the max length :
max_length = max([len(i) for i in seq])
max_length

10

In [14]:
# pad sequence to ensure uniform lenght :
pad_seq = sequence.pad_sequences(seq, maxlen=max_length, padding="post")

In [15]:
# x_train ka data:
pad_seq

array([[ 3,  6,  7,  4,  8,  0,  0,  0,  0,  0],
       [ 2,  9,  1, 10, 11,  2, 12,  1, 13,  0],
       [ 4, 14,  1, 15,  0,  0,  0,  0,  0,  0],
       [ 3, 16, 17, 18, 19,  5, 20, 21, 22, 23],
       [ 2, 24,  1, 25,  5, 26, 27,  0,  0,  0]])

In [16]:
labels = np.array([1 if i=="positive" else 0 for i in settiments])
labels

array([1, 0, 1, 0, 1])

In [17]:
# Define the model :
model = Sequential([
    Embedding(vocab_size, 20, input_length=max_length),
    SimpleRNN(20),
    Dense(1, activation="sigmoid")
])

In [18]:
# Compile the model :
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [19]:
# Train the model :
model.fit(pad_seq, labels, epochs=15, verbose=1)

Epoch 1/15


1/1 [==============================] - 3s 3s/step - loss: 0.7466 - accuracy: 0.2000
Epoch 2/15
1/1 [==============================] - 0s 22ms/step - loss: 0.7221 - accuracy: 0.2000
Epoch 3/15
1/1 [==============================] - 0s 17ms/step - loss: 0.6985 - accuracy: 0.4000
Epoch 4/15
1/1 [==============================] - 0s 18ms/step - loss: 0.6756 - accuracy: 0.4000
Epoch 5/15
1/1 [==============================] - 0s 32ms/step - loss: 0.6534 - accuracy: 0.6000
Epoch 6/15
1/1 [==============================] - 0s 31ms/step - loss: 0.6317 - accuracy: 1.0000
Epoch 7/15
1/1 [==============================] - 0s 17ms/step - loss: 0.6105 - accuracy: 1.0000
Epoch 8/15
1/1 [==============================] - 0s 16ms/step - loss: 0.5895 - accuracy: 1.0000
Epoch 9/15
1/1 [==============================] - 0s 9ms/step - loss: 0.5689 - accuracy: 1.0000
Epoch 10/15
1/1 [==============================] - 0s 15ms/step - loss: 0.5484 - accuracy: 1.0000
Epoch 11/15
1/1 [=============

In [20]:
new_sent = "I was blown away by the incredible performance and gripping storyline"

In [21]:
new_seq =tokens.texts_to_sequences([new_sent])

In [23]:
new_pad_seq = sequence.pad_sequences(new_seq, maxlen=max_length, padding="post")

In [25]:
new_pad_seq

array([[ 3,  1,  2, 11,  0,  0,  0,  0,  0,  0]])

In [27]:
pred = model.predict(new_pad_seq)

1/1 [==============================] - 0s 385ms/step


In [28]:
sentiment = "positive" if pred >= 0.5 else "negative"

In [29]:
sentiment

'positive'