# 𝐑𝐞𝐬𝐭𝐫𝐢𝐜𝐭𝐞𝐝 𝐁𝐨𝐥𝐭𝐳𝐦𝐚𝐧𝐧 𝐌𝐚𝐜𝐡𝐢𝐧𝐞 - (𝐑𝐁𝐌) :

In [1]:
# Import library :
from sklearn.neural_network import BernoulliRBM
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
import numpy as np

In [2]:
# Create data :
data = make_classification(n_samples=1000, n_classes=3, n_features=10, n_informative=7)

In [3]:
data[0]

array([[ 1.23599403, -0.09648612, -0.16112747, ..., -0.87605341,
        -0.44132447, -1.64013847],
       [-1.31764019, -0.04406231,  0.98326678, ...,  1.1679573 ,
        -1.5297466 , -1.26211275],
       [ 0.56076723,  0.36289565, -1.04781367, ..., -0.5500784 ,
         0.21168783, -1.75611425],
       ...,
       [ 1.14867496,  0.43262976,  1.78916118, ...,  0.68866736,
         1.66158122, -0.38431516],
       [-1.00556582, -1.31433131, -2.77104347, ...,  0.7089816 ,
         0.26663135, -4.25568982],
       [ 2.62067657,  1.62399026,  1.64556585, ..., -4.57268595,
         0.4632042 , -0.24940329]])

In [4]:
data[1]

array([1, 2, 2, 0, 2, 2, 2, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 0, 1, 0,
       2, 2, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1, 0, 1, 2, 2,
       1, 1, 1, 0, 2, 2, 1, 1, 2, 1, 2, 1, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2,
       2, 0, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 2, 0, 1, 2, 2, 2, 1, 2, 2,
       1, 1, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0,
       1, 0, 0, 2, 2, 1, 1, 2, 0, 1, 1, 1, 0, 2, 1, 0, 0, 2, 0, 0, 1, 0,
       2, 0, 1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 2, 1, 1, 2, 1, 1, 1, 0, 0,
       1, 2, 2, 0, 1, 1, 2, 2, 1, 2, 0, 0, 0, 1, 2, 1, 2, 2, 0, 0, 1, 1,
       1, 2, 0, 0, 2, 2, 0, 0, 2, 1, 2, 2, 1, 2, 2, 0, 2, 2, 1, 2, 0, 0,
       1, 1, 1, 0, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 0, 2, 0,
       1, 2, 2, 2, 1, 2, 1, 1, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 1, 0, 2, 1,
       1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 0,
       1, 0, 2, 2, 0, 1, 1, 1, 0, 1, 2, 0, 2, 2, 1,

In [5]:
x = data[0]
y = data[1]

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
# Initialize a StandardScaler :
scaler = StandardScaler()

In [8]:
# Fit the StandardScaler to the data in 'x' :
x = scaler.fit_transform(x)

In [9]:
# Compute and return the mean :
x.mean()

-2.842170943040401e-18

In [10]:
# Compute & return standard deviation :
x.std()

1.0

- 𝐋𝐨𝐠𝐢𝐬𝐭𝐢𝐜 𝐑𝐞𝐠𝐫𝐞𝐬𝐬𝐢𝐨𝐧 :

In [12]:
# Create the model :
model = LogisticRegression()

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=12)

In [15]:
# Train the model :
model.fit(x_train, y_train)

LogisticRegression()

In [16]:
# Predict the model :
y_pred = model.predict(x_test)

In [17]:
from sklearn.metrics import f1_score

In [19]:
# print f1-score :
f1_score(y_pred, y_test, average=None)

array([0.79096045, 0.70588235, 0.70588235])

- 𝐁𝐞𝐫𝐧𝐨𝐮𝐥𝐥𝐢𝐑𝐁𝐌 :

In [20]:
# Initalize a BernoulliRBM with 5 hidden components and 100 iteration for training :
RBM = BernoulliRBM(n_components=5, n_iter=100)

In [21]:
x_train = RBM.fit_transform(x_train)

In [22]:
x_test = RBM.fit_transform(x_test)

In [24]:
model2 = LogisticRegression()

In [25]:
model2.fit(x_train, y_train)

LogisticRegression()

In [26]:
y_pred2 = model2.predict(x_test)

In [27]:
f1_score(y_pred2, y_test, average=None)

array([0.02272727, 0.63414634, 0.58937198])

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
# Accuracy Score :
accuracy_score(y_pred2, y_test)

0.508

In [30]:
accuracy_score(y_pred, y_test)

0.736

In [31]:
model2.score(x_train, y_train)

0.49466666666666664